name: .NET Core

on: [push]

jobs:
  build:
    
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        dotnet: [ '3.1.100', '3.1.101' ]
        os: [ubuntu-16.04, ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
          dotnet-version: ${{ matrix.dotnet }}
    - name: Build
      run: dotnet build src
    - name: Run tests
      run: dotnet test src
